### PR TITLE
chore: Add `watch` command to automatically reload during development.

### PR DESCRIPTION
**Pull request by imnotjames**
It's helpful to have an automatic reloading and re-starting command available during development.

To accomplish that, this PR adds `watch` and `start` commands to the `package.json` file.  This utilizes `tsc-watch` to accomplish the watching functionality.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by imnotjames** [comment]
Seems to work for me.  Marking as ready.

**Comment by philnash** [comment]
Hi @imnotjames, I think we might not have been exactly clear in #53. We need the watch mode to be something that someone using `twilio-run` in their project can run. And it shouldn't be watching the `twilio-run` project, but the project in which `twilio-run` is serving files.

Having said that, this is not necessarily a bad thing in this project too. Though I'll leave that up to @dkundel.

**Comment by imnotjames** [comment]
Aha, my misunderstanding.  I'll remove the `closes` message and investigate a more appropriate solution that matches the intended action.

**Comment by dkundel** [comment]
Thanks for the contribution @imnotjames! I can see that you opened another PR with the intended action for #53. I don't think there's much of a benefit to re-run the script when the build works. I typically run `npx tsc --watch` in one tab and try to run the script in a separate one since this is a CLI. So I'll close this PR. Thank you!

**Pull request closed without merging**
