### PR TITLE
Fixing issue with getSync in runtime

### PR DESCRIPTION
**Pull request by ShelbyZ**
- needed default serviceName not object destructuring

### CODE REVIEW

**Comment by dkundel** [comment]
Hi @ShelbyZ sorry for the delay here but I think at least according to the docs you are supposed to pass in `getSync({ serviceName: 'something' })` and therefore it should be destructured here.

https://www.twilio.com/docs/runtime/client?code-sample=code-get-an-existing-sync-document-12&code-language=Node.js&code-sdk-version=default

**Comment by ShelbyZ** [comment]
It looks like that line of code is trying to provide a default value for serviceName.  The call does not set the value of serviceName to 'default' so later ```return client.sync.services(serviceName);``` will have undefined for the value of serviceName.

**Comment by dkundel** [comment]
Oh yeah my bad. So the code should be

```
  function getSync(syncService) {
    syncInfo = syncInfo || { serviceName: 'default' };
    const client = twilio(env.ACCOUNT_SID, env.AUTH_TOKEN);
    return client.sync.services(serviceName);
  }
```

**Comment by ShelbyZ** [comment]
```function getSync(syncService) {
    syncInfo = syncService || { serviceName: 'default' };
    const client = twilio(env.ACCOUNT_SID, env.AUTH_TOKEN);
    return client.sync.services(syncInfo.serviceName);
  }```

The call to ```client.sync.services(syncInfo.serviceName);``` - is either 'default' or the sync service sid

**Comment by dkundel** [comment]
Yeah that should be the behavior

**Comment by dkundel** [comment]
Thank you so much for the fix! I'll publish a new version of 1.x later 😊

**Pull request merged**
